name: Gstreamer Base Build Contaienr Debian ARM64

permissions:
  contents: write
  packages: write

on:
  workflow_dispatch:

env:
  debianVersion: questing

jobs:
  debian:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Clone repo
        uses: actions/checkout@v5

      - name: Setting chroot
        run: |
          # sudo apt update
          install -m 755 arch-bootstrap.sh /usr/local/bin/arch-bootstrap
          # sudo apt install debootstrap -y
          cd /tmp
          if ! sudo arch-bootstrap -a aarch64 archlinux ; then
            echo "基础容器创建失败！"
            exit 1
          fi
          sudo chroot archlinux cat /etc/os-release
