name: Gstreamer Base Build Contaienr ARM64

permissions:
  contents: write
  packages: write

on:
  workflow_dispatch:

jobs:
  archlinux:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Clone repo
        uses: actions/checkout@v5
        with:
          sparse-checkout: |
            arch-bootstrap.sh
            Gst-bcc.sh
            mount.sh


      - name: Setting chroot
        run: |
          # sudo apt update
          install -m 755 arch-bootstrap.sh /usr/local/bin/arch-bootstrap
          # sudo apt install debootstrap -y
          cd /tmp
          if ! sudo arch-bootstrap -a aarch64 archlinux ; then
            echo "基础容器创建失败！"
            exit 1
          fi
          bash mount.sh mount archlinux
          chmod 777 Gst-bcc.sh
          cp Gst-bcc archlinux/bin/
          sudo chroot archlinux Gst-bcc.sh
          cd /tmp
          bash mount.sh unmount archlinux

      - name: Package
        run: |
          cd /tmp
          tar -I 'xz -T$(nproc)' -cf gst-bcc.tar.xz archlinux

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: Gstreamer BCC
          draft: false
          prerelease: false
          tag_name: gst-bcc-latest
          body: |
            Gstreamer BCC
          files: /tmp/gst-bcc.tar.xz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
